/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatapplication;

import static chatapplication.MulticastClient.name;
import static chatapplication.MulticastClient.s;
import java.net.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;



/**
 *
 * @author Pinder
 */
public  class MulticastClient extends javax.swing.JFrame {
 public static String name;
public static String message;
public static MulticastSocket socket=null;
public static InetAddress address ;  
public static DatagramSocket s=null;
/**
     * Creates new form MulticastServerThread
     */
    public MulticastClient()  {
        initComponents();
       this.setLocationRelativeTo(null);
       setupTypingListener(); 

    
            
      
}  
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        typingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel1.setText("Enter  your  message  here");

        jButton2.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jButton2.setText("Exit from Chat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setText("Chat Window");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel3.setText("Online users");

        jButton3.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jButton3.setText("Emoji");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        typingLabel.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jButton2))
                                    .addComponent(jButton3)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(typingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
         String x="========== "+name+" has logged out from the chat room ==========";
         
            byte buf[]=x.getBytes();
              try{  InetAddress group = InetAddress.getByName("230.0.0.1");
                DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
              
             
               s.send(packet);
              }catch(Exception e){}
        x="exited";
        buf=x.getBytes();
        try{
        InetAddress group=InetAddress.getByName("230.0.0.2");
        DatagramPacket packet=new DatagramPacket(buf, buf.length,group,5000);
        s.send(packet);
            
          socket.leaveGroup(address);
           s.close();
     
          }
           catch(Exception e){}
        this.setVisible(false);
           new ChatApp().setVisible(true);   
        
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String time = new SimpleDateFormat("HH:mm").format(new Date());
        

        String text= jTextArea2.getText();
        String formatted = "[" + time + "] " + name + ": " + text;
         if(!text.equals(""))
         {    message=formatted;
    
         try {
             
                byte[] buf ;
 
                  
                                 
                   
                buf = message.getBytes();
             
            // send it
          
                InetAddress group = InetAddress.getByName("230.0.0.1");
                DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
               
              s.send(packet);  
            
           
               }       
         catch (IOException e) {
               // System.out.println(e);
                 MulticastClient.socket.close();
         }   }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String[] emojis = {":)", ":D", ":(", ":O", ":P",
    ";)", ":'(", ":')", ":3", "xD",
    ":|", ":/", ":>", ":<", ">.<",
    ">:(", ">:)","<3", "</3", ":^)", "(^_^)", "(>_<)", "(o_o)", "(-_-)", "(^o^)",
    "T_T", "O_O", "x_x", "-_-;", "(^_-) ",
    "('_')", "(._.)", "(^^;)", "(^.^)", "(^_^)v" };
        JPopupMenu emojiMenu = new JPopupMenu();

        for (String e : emojis) {
            JMenuItem item = new JMenuItem(e);
            item.addActionListener(ev -> {
                jTextArea2.setText(jTextArea2.getText() + e);
            });
            emojiMenu.add(item);
        }

        // SHOW POPUP FROM jButton3 (the real button)
        emojiMenu.show(jButton3, 0, jButton3.getHeight());
    }//GEN-LAST:event_jButton3ActionPerformed
    public void sendTypingStatus(boolean isTyping) {
        try {
            String msg = (isTyping ? "TYPING:" : "STOP_TYPING:") + name;

            byte[] buf = msg.getBytes();
            InetAddress group = InetAddress.getByName("230.0.0.3");
            DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 6000);

            socket.send(packet);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                    new MulticastClient().setVisible(true);
                
                    }
               }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    public static javax.swing.JTextArea jTextArea3;
    public javax.swing.JLabel typingLabel;
    // End of variables declaration//GEN-END:variables

    private void setupTypingListener() {
        jTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {
            private java.util.Timer timer = new java.util.Timer();

            @Override
            public void keyPressed(java.awt.event.KeyEvent e) {
                sendTypingStatus(true);
                restartStopTimer();
            }

            private void restartStopTimer() {
                timer.cancel();
                timer = new java.util.Timer();
                timer.schedule(new java.util.TimerTask() {
                    @Override
                    public void run() {
                        sendTypingStatus(false);
                    }
                }, 1200);
            }
        });
    }
    
 

 class Client implements Runnable {
  
     Client(){
         try{
         MulticastClient.socket = new MulticastSocket(4446) ;
        MulticastClient. s=new DatagramSocket();
        
        MulticastClient. address=InetAddress.getByName("230.0.0.1");
      MulticastClient.socket.joinGroup(MulticastClient.address);
      }
        catch(Exception e)
        {JOptionPane.showMessageDialog(new ChatApp(), "Sorry,Cannot bind");}}
  @Override
  public void run(){
      
      Thread t3=new Thread(new OnlineStatus());
         
           t3.start();
       Thread t4=new Thread(new ReceiveOnlineStatus());
            t4.start();
       new Thread(new TypingReceiver()).start();

       newUser();
           
     
           
  
      
  while(true)
      {  
          
      try{
    
      
         
     
         DatagramPacket packet;
       
         
         
         byte[] buf = new byte[256];
         packet = new DatagramPacket(buf, buf.length);
         
           MulticastClient.socket.receive(packet);
        
         String received = new String(packet.getData(), 0, packet.getLength());
         
     MulticastClient.jTextArea1.setText(MulticastClient.jTextArea1.getText()+received+"\n");
        
        MulticastClient.jTextArea2.setText("");
                  }catch(IOException e){System.err.println(e);}
       }  
 
 
 } void newUser(){String x="========== "+name+" has logged into the chat room ==========";
            byte buf[]=x.getBytes();
              try{  InetAddress group = InetAddress.getByName("230.0.0.1");
                DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
              
             
               s.send(packet);
              }catch(Exception e){}}
  }
    class TypingReceiver implements Runnable {
       @Override
       public void run() {
           try {
               MulticastSocket typingSocket = new MulticastSocket(6000);
               InetAddress group = InetAddress.getByName("230.0.0.3");
               typingSocket.joinGroup(group);

               byte[] buf = new byte[256];

               while (true) {
                   DatagramPacket packet = new DatagramPacket(buf, buf.length);
                   typingSocket.receive(packet);

                   String msg = new String(packet.getData(), 0, packet.getLength());

                   if (msg.startsWith("TYPING:")) {
                       String user = msg.substring(7);
                       if (!user.equals(MulticastClient.name)) {
                           typingLabel.setText(user + " is typing...");
                       }
                   }
                   else if (msg.startsWith("STOP_TYPING:")) {
                       typingLabel.setText("");
                   }
               }
           } catch (Exception e) {
               e.printStackTrace();
           }
       }
   }
}








   
               

